Repository owncloud/templateeditor, pull requests merged in 2018-12, with the labels that each got.

#90 Release 0.4.0
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To Review

#94 Add README.md
  Makefile
  README.md
Labels: 4 - To Release, QA-team

#91 Standardize CI
  .drone.yml
  .gitignore
  .phan/config.php
  .php_cs.dist
  .travis.yml
  Makefile
  README.md
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Http/MailTemplateResponse.php
  lib/MailTemplate.php
  phpstan.neon
  phpunit.xml
  templates/settings-admin.php
  tests/unit/TemplateEditorTest.php
  tests/unit/bootstrap.php
  tests/unit/phpunit.xml
  vendor-bin/owncloud-codestyle/composer.json
  vendor-bin/phan/composer.json
  vendor-bin/phpstan/composer.json
Labels: 4 - To Release, Drone, QA-team
